version: "3.9"

services:
    pytorch-opencv-jupyter:
        container_name: P1_Facial_Keypoints
#        container_name: P1_Facial_Keypoints_DELETE
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        ports:
            - 8888:8888
        command: ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
        volumes:
            - .:/workspace
        image: pytorch-opencv-jupyter:latest
#        image: pytorch-opencv-jupyter:new_DELETE
        build: .
volumes:
    .:
        external:
            name: .
